apiVersion: v1
kind: ResourceQuota
metadata:
  name: high
  namespace: kind
spec:
  hard:
    cpu: "2000"
    memory: 4Gi
    pods: "10"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["high"]